# Generated by Django 6.0 on 2025-12-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('mineral_type', 'Тип полезного ископаемого'), ('stage', 'Этап'), ('work', 'Работа'), ('question', 'Вопрос'), ('faq', 'FAQ')], max_length=50, verbose_name='Тип данных')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('processing', 'В обработке'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('imported_count', models.IntegerField(default=0, verbose_name='Импортировано записей')),
                ('error_count', models.IntegerField(default=0, verbose_name='Ошибок')),
                ('error_details', models.TextField(blank=True, verbose_name='Детали ошибок')),
                ('import_file', models.FileField(blank=True, null=True, upload_to='imports/', verbose_name='Файл импорта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Лог импорта',
                'verbose_name_plural': 'Логи импорта',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataImportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('model_type', models.CharField(choices=[('mineral_type', 'Тип полезного ископаемого'), ('stage', 'Этап'), ('work', 'Работа'), ('question', 'Вопрос'), ('faq', 'FAQ')], max_length=50, verbose_name='Тип данных')),
                ('template_file', models.FileField(upload_to='import_templates/', verbose_name='Файл шаблона')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Шаблон импорта',
                'verbose_name_plural': 'Шаблоны импорта',
            },
        ),
        migrations.CreateModel(
            name='DataValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('mineral_type', 'Тип полезного ископаемого'), ('stage', 'Этап'), ('work', 'Работа'), ('question', 'Вопрос')], max_length=50, verbose_name='Тип данных')),
                ('field_name', models.CharField(max_length=100, verbose_name='Поле')),
                ('rule_type', models.CharField(choices=[('required', 'Обязательное поле'), ('unique', 'Уникальное значение'), ('min_length', 'Минимальная длина'), ('max_length', 'Максимальная длина'), ('regex', 'Регулярное выражение')], max_length=50, verbose_name='Тип правила')),
                ('rule_value', models.CharField(max_length=500, verbose_name='Значение правила')),
                ('error_message', models.CharField(max_length=500, verbose_name='Сообщение об ошибке')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Правило валидации',
                'verbose_name_plural': 'Правила валидации',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('keywords', models.TextField(help_text='Слова для поиска, разделенные запятыми', verbose_name='Ключевые слова (через запятую)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MineralType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тип полезного ископаемого',
                'verbose_name_plural': 'Типы полезных ископаемых',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст вопроса')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код вопроса')),
                ('description', models.TextField(blank=True, verbose_name='Описание вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название этапа')),
                ('code', models.CharField(max_length=50, verbose_name='Код этапа')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('duration_months', models.IntegerField(default=1, verbose_name='Длительность этапа (месяцев)')),
                ('start_month', models.IntegerField(default=0, verbose_name='Старт этапа (месяц от начала)')),
                ('color', models.CharField(default='#0070C0', max_length=7, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserGanttChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('chart_data', models.JSONField(default=dict, verbose_name='Данные диаграммы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Диаграмма Ганта',
                'verbose_name_plural': 'Диаграммы Ганта',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер работы')),
                ('title', models.CharField(max_length=500, verbose_name='Название работы')),
                ('description', models.TextField(blank=True, verbose_name='Описание работы')),
                ('executor', models.CharField(max_length=300, verbose_name='Исполнитель')),
                ('duration_months', models.IntegerField(default=1, verbose_name='Длительность (месяцев)')),
                ('start_month', models.IntegerField(default=0, verbose_name='Старт (месяц от начала этапа)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок в этапе')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'ordering': ['order'],
            },
        ),
    ]
