# Generated by Django 6.0 on 2025-12-10 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roadmap_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimportlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='question',
            name='mineral_types',
            field=models.ManyToManyField(related_name='questions', to='roadmap_app.mineraltype', verbose_name='Доступно для типов ПИ'),
        ),
        migrations.AddField(
            model_name='stage',
            name='depends_on',
            field=models.ManyToManyField(blank=True, help_text='Этапы, которые должны быть завершены перед началом этого', related_name='dependent_stages', to='roadmap_app.stage', verbose_name='Зависит от'),
        ),
        migrations.AddField(
            model_name='stage',
            name='mineral_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='roadmap_app.mineraltype', verbose_name='Тип ПИ'),
        ),
        migrations.AddField(
            model_name='question',
            name='target_stages',
            field=models.ManyToManyField(help_text='До каких этапов нужно дойти для решения вопроса', related_name='target_questions', to='roadmap_app.stage', verbose_name='Целевые этапы'),
        ),
        migrations.AddField(
            model_name='userganttchart',
            name='mineral_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roadmap_app.mineraltype', verbose_name='Тип полезного ископаемого'),
        ),
        migrations.AddField(
            model_name='userganttchart',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roadmap_app.question', verbose_name='Целевой вопрос'),
        ),
        migrations.AddField(
            model_name='userganttchart',
            name='start_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_charts', to='roadmap_app.stage', verbose_name='Начальный этап'),
        ),
        migrations.AddField(
            model_name='userganttchart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gantt_charts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='work',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='roadmap_app.stage', verbose_name='Этап'),
        ),
        migrations.AlterUniqueTogether(
            name='stage',
            unique_together={('mineral_type', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='work',
            unique_together={('stage', 'number')},
        ),
    ]
